version: "3.8"

services:
  api:
    build:
      context: "api/"
      dockerfile: "Dockerfile"
    container_name: api
    volumes:
      - ./api:/app
    ports:
      - 8000:8000

  web:
    build:
      context: "web/"
      dockerfile: "Dockerfile"
    container_name: web
    volumes:
      - "/app/node_modules"
      - ./web:/app
    ports:
      - 3000:3000
